<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <IncludePath>..\..;..\..\..\com0com\include;$(VC_IncludePath);$(WindowsSDK_IncludePath)</IncludePath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
      <PreprocessorDefinitions>_CRT_SECURE_NO_DEPRECATE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <PrecompiledHeader>Use</PrecompiledHeader>
      <PrecompiledHeaderFile>precomp.h</PrecompiledHeaderFile>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <AdditionalDependencies>ws2_32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <ModuleDefinitionFile>..\plugins.def</ModuleDefinitionFile>
      <OutputFile>$(OutDir)plugins\$(ProjectName).dll</OutputFile>
    </Link>
  </ItemDefinitionGroup>
</Project>
